export const WEBSOCKET_MAX_RECONNECT_ATTEMPTS = 3;

export const WEBSOCKET_MAX_FIRST_RECONNECT_ATTEMPTS = 0;

export const WEBSOCKET_RECONNECT_BASE_DELAY_MS = 1_000;

export const WEBSOCKET_RECONNECT_MAX_DELAY_MS = 30_000;

export const WEBRTC_STUN_SERVER = "stun:stun.l.google.com:19302";

export const WEBRTC_DATA_CHANNEL_NAME = "clipboard";

export const WEBRTC_MAX_RESTART_ATTEMPTS = 3;

export const WEBRTC_MAX_FIRST_RESTART_ATTEMPTS = 0;

export const WEBRTC_RESTART_BASE_DELAY_MS = 2_000;

export const WEBRTC_RESTART_MAX_DELAY_MS = 60_000;

export const WEBRTC_DISCONNECTED_GRACE_MS = 5_000;

export const LOGS_MAX_ENTRIES = 200;

export const DEFAULT_PING_INTERVAL_MS = 30_000;

export const DEFAULT_POLLING_INTERVAL_MS = 1_000;
