name: "Pull Request"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  client-checks:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          setup-tauri: "true"

      - name: Build
        run: pnpm build --filter @clipboard-sync/client

      - name: Check
        run: pnpm check --filter @clipboard-sync/client

  server-checks:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm build --filter @clipboard-sync/server

      - name: Check
        run: pnpm check --filter @clipboard-sync/server

  update-server-checks:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm build --filter @clipboard-sync/update-server

      - name: Check
        run: pnpm check --filter @clipboard-sync/update-server
